### PR TITLE
Add support for extended baudrates on posix systems (57600-4000000)

### LINKED ISSUE #4: Need support baud rate greater than 38400 on posix systems.
pyserial does this:
https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py

### PR DESCRIPTION
**Pull request by Jeff-Ciesielski**
Closes #4 

Caveat: This requires https://github.com/nim-lang/Nim/pull/8322, and therefore should probably wait until the 0.19.0 release to merge and update version numbers.  

If you'd prefer, I can hold off making this PR until the new release, otherwise it's fine by me if this just collects dust until then.  I'm motivated to keep track since this is for a work project.

### CODE REVIEW

**Comment by euantorano** [comment]
We can also add a when check for NimMajor, NimMinor and NimPatch and feature gate it that way. I’m happy with either option

**Comment by euantorano** [comment]
This looks good otherwise though.

I want to think up a better way than what's currently there to do this translation. I also want to change `baudRate*` to use a `case` rather than `if/else`.

I also want to add support for custom baud rates on the platforms that support them, just need to work out the best way to do that (it may require runtime checks).

**Comment by Jeff-Ciesielski** [comment]
Typically for stuff like this I like to use bidirectional tables and just trap the KeyError on a failed lookup.  I'd be happy to make that change.

**Comment by euantorano** [comment]
I'm going to merge this for now, and look at improving it this weekend. Thanks!

**Pull request merged**
